### ISSUE TITLE
extract_all.py fails when a comment has no icon

### ISSUE THREAD

**Issue by dhouck** [ssafar/effulgence2epub#2]
This is rare in Effulgence; the first occurence is in 46.3 Doors are Complicated, page 12. The published ebooks on Alicornutopia are missing Doors are Complicated as a result; `gen_ebook` exits with an error on that chapter. Even after correcting `extract_all.py`, `gen_ebook`  still can’t assumes all comments have images (in several places).

**Comment by ssafar** [comment]
... oookay, github is smart and parses commit messages. Nice to know. Anyway, we don't assume images for everywhere anymore. Instead, we fill up space with an embedded 1x1 gif resized to 100x100; works nicely both in Chrome and on a Kindle.

**Comment by dhouck** [comment]
Looks good; I’ll update the changesets in my pull request to handle it that way, whhich looks like it’ll work more nicely.
