### ISSUE TITLE
License agreement

### ISSUE THREAD

**Issue by dhouck** [ssafar/effulgence2epub#3]
You’re trying to license this under the 3-clause BSD (I prefer the MIT, but they’re practically equivalent). However, EbookLib is licensed under the AGPL, and I’m pretty sure that’s copyleft in the same manner as the regular GPL. Since your README file indicates you’re not completely happy with EbookLib anyway, you might prefer to replace that then to relicense. Everything else you use as a library is MIT licensed.

In any case, this seems like the kind of thing it’s much easier to address earlier than later. Unfortunately, I don’t have any suggestions for alternate ebook libraries (except calibre, which is huge and I think this project would be better not using it as a dependency).

**Comment by ssafar** [comment]
Actually, I think we could get away without any ebook library whatsoever... epubs are basically zip files with some xml in them, generating it doesn't look too hard. Nevertheless, for the time being, AGPL it is :)
